x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

services:
  devrunner:
    build: runner/
    hostname: runner
    env_file: .env
    ports:
      - 2222:2222
    volumes:
       - ../app:/home/sofi:rw
    container_name: runner
    <<: *logging
